name: build
on:
  push:
    branches:
      - main
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
  merge_group:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    # Apply this label to bypass changed-module filtering for a pull request.
    if: github.event.action != 'labeled' || github.event.label.name == 'rebuild-all-images'
    permissions:
      packages: write # needed to publish packages
    strategy:
      fail-fast: false
      matrix:
        build_script:
          - ./build-individual.nu
          - ./build-unified.nu
    uses: ./.github/workflows/build-reusable.yml
    with:
      build_script: ${{ matrix.build_script }}
      rebuild_all_images: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'rebuild-all-images') }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
